In [1]:
#Import dependencies
import pandas as pd
import numpy as np
import random

In [2]:
# Read in wine data
wine_df = pd.read_csv("wine.csv")
wine_df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
0,7.5,0.33,0.32,11.1,0.036,25.0,119.0,0.99620,3.15,0.34,10.5,6
1,6.3,0.27,0.29,12.2,0.044,59.0,196.0,0.99782,3.14,0.40,8.8,6
2,7.0,0.30,0.51,13.6,0.050,40.0,168.0,0.99760,3.07,0.52,9.6,7
3,7.4,0.38,0.27,7.5,0.041,24.0,160.0,0.99535,3.17,0.43,10,5
4,8.1,0.12,0.38,0.9,0.034,36.0,86.0,0.99026,2.80,0.55,12,6
...,...,...,...,...,...,...,...,...,...,...,...,...
2032,8.1,0.34,0.28,7.5,0.040,70.0,230.0,0.99558,3.14,0.55,9.8,6
2033,7.4,0.19,0.31,14.5,0.045,39.0,193.0,0.99860,3.10,0.50,9.2,6
2034,6.7,0.36,0.26,7.9,0.034,39.0,123.0,0.99119,2.99,0.30,12.2,7
2035,7.7,0.28,0.35,15.3,0.056,31.0,117.0,0.99980,3.27,0.50,9.6,5
2036,5.7,0.22,0.28,1.3,0.027,26.0,101.0,0.98948,3.35,0.38,12.5,7

In [3]:
# Create "Wine Region" column with random wine type dispersed randomly.

wine_df["Wine Region"] = pd.Series(
    random.choices(["Minho", "Dao", "Beira Atlantico", "Lisboa", "Tejo", "Setubal", "Madeira", "Algarve", "Alentejo",
                    "Beira Interior", "Terras De Cister", "Douro Valley", "Transmontano",  ], weights=[1, 1, 1, 1, 1, 1,
                    1, 1, 1, 1, 1, 1, 1], k=len(wine_df)),
    index=wine_df.index
)
wine_df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,Wine Region
0,7.5,0.33,0.32,11.1,0.036,25.0,119.0,0.99620,3.15,0.34,10.5,6,Terras De Cister
1,6.3,0.27,0.29,12.2,0.044,59.0,196.0,0.99782,3.14,0.40,8.8,6,Alentejo
2,7.0,0.30,0.51,13.6,0.050,40.0,168.0,0.99760,3.07,0.52,9.6,7,Alentejo
3,7.4,0.38,0.27,7.5,0.041,24.0,160.0,0.99535,3.17,0.43,10,5,Setubal
4,8.1,0.12,0.38,0.9,0.034,36.0,86.0,0.99026,2.80,0.55,12,6,Terras De Cister
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2032,8.1,0.34,0.28,7.5,0.040,70.0,230.0,0.99558,3.14,0.55,9.8,6,Dao
2033,7.4,0.19,0.31,14.5,0.045,39.0,193.0,0.99860,3.10,0.50,9.2,6,Alentejo
2034,6.7,0.36,0.26,7.9,0.034,39.0,123.0,0.99119,2.99,0.30,12.2,7,Madeira
2035,7.7,0.28,0.35,15.3,0.056,31.0,117.0,0.99980,3.27,0.50,9.6,5,Beira Atlantico
2036,5.7,0.22,0.28,1.3,0.027,26.0,101.0,0.98948,3.35,0.38,12.5,7,Algarve

In [6]:
# Create "Wine Color" column with the three typical colors dispersed randomly. 

wine_df["Wine Color"] = pd.Series(random.choices(["Red", "White", "Rose"], weights=[1, 1, 1,], k=len(wine_df)),
                                  index=wine_df.index)

wine_df

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,Wine Region,Wine Color
0,7.5,0.33,0.32,11.1,0.036,25.0,119.0,0.99620,3.15,0.34,10.5,6,Terras De Cister,Rose
1,6.3,0.27,0.29,12.2,0.044,59.0,196.0,0.99782,3.14,0.40,8.8,6,Alentejo,Red
2,7.0,0.30,0.51,13.6,0.050,40.0,168.0,0.99760,3.07,0.52,9.6,7,Alentejo,Red
3,7.4,0.38,0.27,7.5,0.041,24.0,160.0,0.99535,3.17,0.43,10,5,Setubal,White
4,8.1,0.12,0.38,0.9,0.034,36.0,86.0,0.99026,2.80,0.55,12,6,Terras De Cister,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2032,8.1,0.34,0.28,7.5,0.040,70.0,230.0,0.99558,3.14,0.55,9.8,6,Dao,White
2033,7.4,0.19,0.31,14.5,0.045,39.0,193.0,0.99860,3.10,0.50,9.2,6,Alentejo,Rose
2034,6.7,0.36,0.26,7.9,0.034,39.0,123.0,0.99119,2.99,0.30,12.2,7,Madeira,Rose
2035,7.7,0.28,0.35,15.3,0.056,31.0,117.0,0.99980,3.27,0.50,9.6,5,Beira Atlantico,Red
2036,5.7,0.22,0.28,1.3,0.027,26.0,101.0,0.98948,3.35,0.38,12.5,7,Algarve,Red

In [8]:
wine_df.to_csv("Wine_RegionColor.csv", index=False)